name: easycatalog
description: "Catálogo digital personalizable HyJ Souvenir Bisutería"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # 📦 Base de datos local
  sqflite: ^2.3.3
  path_provider: ^2.1.2
  path: ^1.9.0

  # 📄 PDF y vista previa
  pdf: ^3.10.5
  printing: ^5.12.0
  barcode: ^2.2.5

  # 🎨 Selector de color moderno
  flutter_colorpicker: ^1.0.3

  # 📷 Carga de imágenes y logos
  image_picker: ^1.1.1

  # 💾 Guardar PDF local
  file_picker: ^8.1.4

  # 🔗 Compartir PDF (WhatsApp, AirDrop, etc.)
  share_plus: ^10.0.0

  # 💡 Utilidades
  intl: ^0.19.0
  shared_preferences: ^2.3.1
  flutter_launcher_icons: ^0.14.4
  flutter_image_compress: ^2.4.0
  # Tamaño de la ventana Apps
  window_size: ^0.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.2

flutter:
  uses-material-design: true

  assets:
    - assets/icons/EasyCatalogIcon-iOS-Default-1024x1024@1x.png
    - assets/fonts/

  fonts:
    - family: PlaylistScript
      fonts:
        - asset: assets/fonts/PlaylistScript.otf

    - family: BukhariScript
      fonts:
        - asset: assets/fonts/BukhariScript.ttf

    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat-Regular.ttf
        - asset: assets/fonts/Montserrat-Bold.ttf
          weight: 700

    - family: OpenSans
      fonts:
        - asset: assets/fonts/OpenSans-Regular.ttf
        - asset: assets/fonts/OpenSans-SemiBold.ttf
          weight: 600
flutter_launcher_icons:
  android: false
  ios: false

  macos:
    generate: true
    image_path: "assets/icons/EasyCatalogIcon-iOS-Default-1024x1024@1x.png"
    background_color: "#FFFFFF"

  image_path: "assets/icons/EasyCatalogIcon-iOS-Default-1024x1024@1x.png"
  remove_alpha_ios: true
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "assets/EasyCatalogIcon-iOS-Default-1024x1024@1x.png"
